apiVersion: v2
name: peekaping
version: 1.0.0
dependencies:
- name: valkey
  version: "2.2.2"
  repository: https://groundhog2k.github.io/helm-charts/
  condition: valkey.enabled

- name: postgresql
  version: 18.1.13
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: postgresql.enabled
